version: '3.7'

services:

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    entrypoint: ['/app/server/start.sh']
    volumes:
      - .:/app
    ports:
      - 8000:80 # local:remote
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/api
    depends_on:
      - db

  db:
    image: postgres:alpine
    expose:
      - 5432
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres